spring:
  threads:
    virtual:
      enabled: true
telegram:
    bot:
      token: ${TELEGRAM_BOT_TOKEN}
      my-chat-id: ${TELEGRAM_MY_CHAT_ID}

web-phone:
    domain: ${WEB_PHONE_DOMAIN}
    username: ${WEB_PHONE_USERNAME}
    password: ${WEB_PHONE_PASSWORD}